USE cleandatabase;
SELECT COUNT(*) FROM clean_table;
SELECT * FROM clean_table LIMIT 10;
alter table clean_table
modify sales decimal(10, 2);
-- 1. Top 10 customers
USE cleandatabase;
select customer, sum(sales) as total_sales
from clean_table
group by customer
order by customer desc
limit 10; 
-- It shows total sales generated by each customer. 
-- Limit 10 shows only top 10 customers.


-- 2. sales by category
USE cleandatabase;
select category, sum(sales) as total_sales
from clean_table
group by category
order by category desc; 
-- It shows how much sales produced by each category. 
-- Technology category generates more revenue.


-- 3. Monthly revenue trend
SELECT DATE_FORMAT(order_date, '%m') AS month,
       SUM(sales) AS monthly_sales
FROM clean_table
GROUP BY month
ORDER BY month desc;  
-- It shows monthly sales trend. 
-- Sales are higher in month of November & December.


-- 4. Repeat purchase rate

SELECT 
    SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) / COUNT(*) AS repeat_purchase_rate
FROM (
    SELECT customer, COUNT(DISTINCT order_id) AS order_count
    FROM clean_table
    GROUP BY customer
) t;  
-- -- It shows the percentage of  customers who place multiple orders.


-- 5. avg. order values
SELECT customer, AVG(total_order_value) AS avg_order_value
FROM clean_table
group by customer
order by avg_order_value desc; 
-- It shows how much customer spend per order on average.
--  By sorting the results in descending order, we can quickly identify our high-value customers.


